spring:
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nasa
    url: jdbc:mysql://localhost:3306/nasa?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true