spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nasa?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    password: nasaAuthorize_123456

    jpa:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nasa
      properties:
        hibernate:
          hbm2ddl:
            auto: update

server:
  ssl:
    enabled: true
    key-store: classpath:bthttps.jks
    key-store-password: bugtelegram