
spring:
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nasa
    url: jdbc:mysql://localhost:3306/nasa?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    password: 123456
  jpa:
    show-sql: true
debug: true

server:
  ssl:
    enabled: true
    key-store: classpath:bthttps.jks
    #key-alias: BugTelegram
    key-store-password: bugtelegram
